---
title: "Test"
author: "Sung Lee"
date: "10/1/2021"
output: html_document
---


```{r}
library(leaflet)
library(leaflet.extras) #for demo heat map
library(geojsonio)
library(maps)
library(ggplot2)
library(dplyr)
library(lubridate)
library(tidyr)
library(forcats)
library(scales)
library(stringr)


data <- read.csv("cleaned-cdc-mortality-1999-2010-2.csv", 
                 sep = ",", 
                 header = TRUE)

head(data)
unique(data$ICD.Chapter)
names(data)
```


```{r}
temp <- data[data$Year == 2010 & data$ICD.Chapter == "Neoplasms",]

temp %>%
  mutate(State = fct_reorder(State, Crude.Rate)) %>%
  ggplot(aes(x=State, y=Crude.Rate)) + 
        geom_bar(stat="identity", fill="firebrick2") +
        #labs(title = paste("Frequency of Licenses by Year for ", input$mapBoro2, sep="")) + 
        xlab("State") +
        ylab("Crude Mortality Rate") +
        coord_flip() +
        theme(panel.grid.major = element_blank(), 
              panel.grid.minor = element_blank(), 
              panel.background = element_blank(), 
              axis.line = element_line(colour = "black") 
              )

```  


```{r}

# Dataframe for the condition
temp <- data[data$ICD.Chapter == "Pregnancy, childbirth and the puerperium",]

# To get the national average
agg_sum <- aggregate(temp[,c("Deaths", "Population")],by=list(temp$Year),FUN=sum, na.rm=TRUE)
agg_sum['NationalAverage'] <- agg_sum$Deaths / agg_sum$Population * 100000

#Year, Deaths, Population, NationalAverage
colnames(agg_sum)[1] <- "Year"

tempState <- temp[temp$State == 'NJ',]
tempState$NationalAverage <- agg_sum$NationalAverage[match(tempState$Year, agg_sum$Year)]

tempState


df5 <- tempState %>% select(Year, Crude.Rate, NationalAverage) %>% gather("Crude", "Value", -Year)

df5 %>% ggplot() + aes(x = Year, y = Value, fill = Crude) +
  geom_col(position = "dodge") +
  ggtitle('Crude Rate vs National Crude Rate') +
  xlab('Year') +
  ylab('Crude Rate') +
  scale_x_continuous(breaks= pretty_breaks()) +
  theme(panel.background = element_rect(fill = "white", color = NA))




```



```{r, eval=TRUE}

# "GEO_ID"     "STATE"      "NAME"       "SHORTNAME"  "CENSUSAREA"
states <- geojson_read("us_states.json", what = "sp")
temp2 <- temp[temp$Year == 2010,]

# Used for replacing NA values
replaceValue <- mean(temp2$Crude.Rate, na.rm=TRUE)

names(states)


states$Crude.Rate <- temp2$Crude.Rate[match(states$SHORTNAME, temp2$State)]
states$Crude.Rate[is.na(states$Crude.Rate)] <- replaceValue




#bins <- c(0, 10, 20, 50, 100, 200, 500, 1000, Inf)
#pal <- colorBin("YlOrRd", domain = states$Crude.Rate, bins = bins)

x <- cut(temp2$Crude.Rate, 3, include.lowest=TRUE)
z <- sapply(str_extract_all(x, "-?[0-9.]+"), function(y) max(as.numeric(y)))
z <- unique(sort(z))
z <- c(0, z, Inf)

bins <- z
pal <- colorBin("YlGn", domain = states$Crude.Rate, bins = bins)

labels <- sprintf(
  "<strong>%s</strong><br/>%g Crude.Rate",
  states$NAME, states$Crude.Rate
) %>% lapply(htmltools::HTML)


leaflet(states) %>%
  setView(-96, 37.8, 4) %>%
  addProviderTiles("MapBox", options = providerTileOptions(
    id = "mapbox.light",
    accessToken = Sys.getenv('pk.eyJ1IjoiY3VueXNzbGVlIiwiYSI6ImNrdTlzNmF4azA5dzYyeG5ubXZvZDRxbzQifQ.Z4cygOgWVTTt9DkUVkCbgw'))) %>%
  addPolygons(
    fillColor = ~pal(Crude.Rate),
    weight = 2,
    opacity = 1,
    color = "white",
    dashArray = "3",
    fillOpacity = 0.7,
    highlightOptions = highlightOptions(
      weight = 5,
      color = "#666",
      dashArray = "",
      fillOpacity = 0.7,
      bringToFront = TRUE),
    label = labels,
    labelOptions = labelOptions(
      style = list("font-weight" = "normal", padding = "3px 8px"),
      textsize = "15px",
      direction = "auto")) %>%
  addLegend(pal = pal, values = ~density, opacity = 0.7, title = NULL,
    position = "bottomright")


```  



```{r, eval=FALSE}
library(stringr)
temp2 <- temp[temp$Year == 2010,]
replaceValue <- mean(temp2$Crude.Rate, na.rm=TRUE)
temp2$Crude.Rate[is.na(temp2$Crude.Rate)] <- replaceValue

x <- cut(temp2$Crude.Rate, 3, include.lowest=TRUE)
z <- sapply(str_extract_all(x, "-?[0-9.]+"), function(y) max(as.numeric(y)))
z <- unique(sort(z))
z
```